### ISSUE TITLE
Merge with type-scale

### ISSUE THREAD

**Issue by robsonsobral** [modularscale/modularscale.com#81]
Hi!

Both [Modular Scale](http://www.modularscale.com/) and @jeremychurch's [Type-scale](http://type-scale.com/) are almost perfect. **Type-scale** has the load of Google Fonts, the font-family and weight customizations and the preview panel. **Modular Scale** has the Sass plugin, the JS code and the multiple bases.

Can't the both be merged? The strengths of Type-Scale could be added to Modular Scale and to become an amazing tool!

Thank you for your attention, everybody.

**Comment by scottkellum** [comment]
Thanks @robsonsobral and while I know there are many similarities some of the core concepts are different. While modular scales are excellent for sizing type, that is why I added text in the preview panel, the focus on modularscale.com is to be more like a ruler than a typesetting tool. Values from this ruler can be used in type as well as other aspects of a design. I have opinions about typesetting but I am focusing those opinions for a different tool that will have some of the features like Google Fonts and Typekit integration as well as modular scales, variable font settings, and more. I want to keep modular scales focused on just being a really good tool for creating modular scales but no more than a glorified ruler and leave opinions on how to use the ruler out of this particular project.
